### ISSUE TITLE
Fresh docker container: SQLITE_ERROR: no such table: Configs

### ISSUE THREAD

**Issue by jwrangel** [MichaelSp/timelimit-server#371]
The error 
```SQLITE_ERROR: no such table: Configs```

shows up after every start of docker container.

Full error log:

```
> timelimit-server@1.17.0 start
> node ./build/index.js

Error
    at Database.<anonymous> (/usr/src/app/node_modules/sequelize/lib/dialects/sqlite/query.js:185:27)
    at /usr/src/app/node_modules/sequelize/lib/dialects/sqlite/query.js:183:50
    at new Promise (<anonymous>)
    at Query.run (/usr/src/app/node_modules/sequelize/lib/dialects/sqlite/query.js:183:12)
    at /usr/src/app/node_modules/sequelize/lib/sequelize.js:315:28
    at async SQLiteQueryInterface.bulkDelete (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:403:12)
    at async Config.destroy (/usr/src/app/node_modules/sequelize/lib/model.js:1838:16)
    at async assertNestedTransactionsAreWorking (/usr/src/app/build/database/utils/nested-transactions.js:34:5)
    at async main (/usr/src/app/build/index.js:32:5) {
  name: 'SequelizeDatabaseError',
  parent: [Error: SQLITE_ERROR: no such table: Configs] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: "DELETE FROM `Configs` WHERE `id` = 'self_test_data'"
  },
  original: [Error: SQLITE_ERROR: no such table: Configs] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: "DELETE FROM `Configs` WHERE `id` = 'self_test_data'"
  },
  sql: "DELETE FROM `Configs` WHERE `id` = 'self_test_data'",
  parameters: {}
}```

**Comment by MichaelSp** [comment]
@jwrangel Did that help? Can we close this?

**Comment by MichaelSp** [comment]
outdated
